unit:
  name: "Goliath"
  role: "Elite, Damage Dealer"
  weapon: "Autocannon, Underbelly Machine Gun, Hellfire Missiles (Upgrade: Scatter Missiles, Haywire Missiles)"
regular_abilities:
  deploy:
    sound_sources: [deploy]
  move:
    sound_sources: [move]
  attack:
    sound_sources: [attack]
  destroyed:
    sound_sources: [death]
additional_abilities:
  missles:
    sound_sources: [missles]
