$registry = @{
    ost = @{
        starcraft1 = @{
            protoss = @()
            terran = @()
            zerg = @()
        }
        starcraft2 = @{
            protoss = @()
            terran = @()
            zerg = @()
        }
    }
    units = @{
        protoss = @{}
        terran = @{}
        zerg = @{}
    }
}

# Find workspace root
$rootPath = Get-Location

# Scan OST
if (Test-Path ost) {
    Get-ChildItem -Path ost -File -Recurse | ForEach-Object {
        $ext = $_.Extension.ToLower()
        if ($ext -eq ".wav" -or $ext -eq ".ogg" -or $ext -eq ".mp3") {
            $relPath = $_.FullName.Substring($rootPath.Path.Length + 1).Replace('\', '/')
            $parts = $relPath.Split('/')
            if ($parts.Count -ge 4) {
                $ver = $parts[1]
                $race = $parts[2]
                if ($registry.ost.ContainsKey($ver) -and $registry.ost.$ver.ContainsKey($race)) {
                    $registry.ost.$ver.$race += $relPath
                }
            }
        }
    }
}

# Scan Units
if (Test-Path units) {
    Get-ChildItem -Path units -File -Recurse | ForEach-Object {
        $ext = $_.Extension.ToLower()
        if ($ext -eq ".wav" -or $ext -eq ".ogg" -or $ext -eq ".mp3") {
            $relPath = $_.FullName.Substring($rootPath.Path.Length + 1).Replace('\', '/')
            $parts = $relPath.Split('/')
            if ($parts.Count -ge 5) {
                $race = $parts[1]
                $unit = $parts[2]
                $action = $parts[3]
                if ($registry.units.ContainsKey($race)) {
                    if (-not $registry.units.$race.ContainsKey($unit)) {
                        $registry.units.$race[$unit] = @{}
                    }
                    if (-not $registry.units.$race[$unit].ContainsKey($action)) {
                        $registry.units.$race[$unit][$action] = @()
                    }
                    $registry.units.$race[$unit][$action] += $relPath
                }
            }
        }
    }
}

# Serialize to JSON string
$json = $registry | ConvertTo-Json -Depth 10

# Write to audio-registry.js as window.AUDIO_REGISTRY
$jsContent = @"
// Automatically generated by generate-registry.ps1. Do not modify manually.
window.AUDIO_REGISTRY = $json;
"@

$jsContent | Out-File -FilePath audio-registry.js -Encoding utf8
Write-Host "audio-registry.js generated successfully!"
