unit:
  name: "immortal"
  role: "Elite, Tank"
  weapon: "Photon Disruptor (Upgrade: Phase Disruptor)"
regular_abilities:
  deploy:
    sound_sources: [deploy]
  move:
    sound_sources: [move]
  attack:
    sound_sources: [attack]
  destroyed:
    sound_sources: [death, deathFX]
    playback: sequential
additional_abilities:
  {}
