unit:
  name: "Zealot"
  role: "Core, Damage Dealer"
  weapon: "Psi Blades"
regular_abilities:
  deploy:
    sound_sources: [deploy]
  move:
    sound_sources: [move]
  melee_combat:
    sound_sources: [combat]
  destroyed:
    sound_sources: [death, deathFX]
    playback: simultaneous
additional_abilities:
  charge:
    sound_sources: [charge]
